"""
   Each new term in the Fibonacci sequence is generated by adding the
   previous two terms. By starting with 1 and 2, the first 10 terms will be:

                     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do not
   exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(n):
    """Generates numbers in the fibonacci sequnce not exceeding n"""
    a, b = 1, 1
    while a <= n:
        yield a
        a, b = b, a + b

if __name__ == '__main__':
    upper_limit = 4000000

    sum_of_even_fibs = 0
    for i in fibonacci(upper_limit):
        if not i % 2:
            sum_of_even_fibs += i

    print(sum_of_even_fibs)
